POST http://localhost:8080/api/v1/images/sync
content-type: application/json

{
  "root": "/Users/ali/Developer/github.com/sika365/admin-toolkit/samples/cat_barcodes",
  "max_depth": 10,
  "content_types": "image/.+",
  "replace": true
}