### Sync by Barcode
POST http://localhost:8080/api/v1/products/sync/images
content-type: application/json

{
  // file scan request
  "root": "",
  "max_depth": 1,
  "content_types": "image/.+",
  "naming_pattern": "",
  // product sync request
  "replace_cover": true,
  "replace_gallery": true,
  "ignore_cover_if_empty": false,
  "ignore_add_to_gallery": false,
  // product scan request
  "cover_naming": "",
  "gallery_naming": "",
  "ignore_match": false
}

### Sync by Spreadsheets
POST http://localhost:8080/api/v1/products/sync/spreadsheets?order_by=newest&check_availability=false&search_products_in_nodes=true&search_in_node=false&search_in_sub_node=false&get_product_parents=false&search_in_reserved_quantity=false&search_in_limited_quantity=false&limit=20&offset=0&cover_status=0&view=node&remote_pagination=false&remote_search=false&includes=Cover&includes=Nodes.Parent.Category&includes=Tags.Node.Category&includes=CategoryNodes&store_id=28&branch_id=32&stock_id=29
content-type: application/json

{
  "root": "/home/ali/github.com/sika365/admin-toolkit-dev/import/bookmall-2024/enabled",
  "max_depth": 1,
  "content_types": ".+",
  "replace_nodes": true,
  "product_header_map": {
    "title": "نام",
    "barcode": "بارکد",
    "category": "گروه کالا"
  }
}

# "product_header_map": {
#   "title": "نام",
#   "barcode": "بارکد",
#   "category": "گروه کالا"
# }
